export const intelligenceViews = ['Overview', 'Requirements', 'Blueprint', 'Traceability', 'Environment', 'Health', 'Snapshot', 'Timeline', 'Drift'] as const;
export type IntelligenceView = typeof intelligenceViews[number];
export type Lifecycle = 'pending' | 'in_progress' | 'completed' | 'blocked';
export type Verification = 'PENDING' | 'PARTIALLY_VERIFIED' | 'VERIFIED' | 'NOT_VERIFIED' | 'INCONCLUSIVE';
export interface ProjectInfo { project_id: string; root_path: string; name: string; created_at: string }
export interface EnvironmentInfo { python_available: boolean; python_executable: string | null; python_version: string | null; virtualenv_present: boolean; virtualenv_path: string | null; virtualenv_usable: boolean; platform: string | null; git_available: boolean; inspection_scope: string }
export interface Requirement { requirement_id: string; title: string; description: string; lifecycle_status: Lifecycle; status: Verification; acceptance_criteria: string[]; implementation_references: string[]; evidence_references: string[] }
export interface Feature { feature_id: string; title: string; description: string; status: Lifecycle; requirement_ids: string[] }
export interface Task { task_id: string; feature_id: string; title: string; description: string; status: Lifecycle; dependencies: string[] }
export interface Blueprint { project_id: string; project_name: string; description: string; generated_at: string; requirements: string[]; features: Feature[]; tasks: Task[]; truncated: boolean }
export interface Implementation { implementation_id: string; file_path: string; module_name: string | null; symbol_name: string | null; symbol_type: string | null; feature_id: string | null; requirement_ids: string[]; evidence_ids: string[] }
export interface TraceTest { test_id: string; file_path: string; test_name: string | null; requirement_ids: string[]; evidence_ids: string[] }
export interface TraceLink { link_id: string; source_id: string; target_id: string; link_type: string; created_at: string; evidence_backed: boolean; is_inferred: boolean }
export interface TraceGraph { project_id: string; requirements: string[]; features: string[]; tasks: string[]; evidence: string[]; implementations: Implementation[]; tests: TraceTest[]; links: TraceLink[]; validation: { valid: boolean; issues: string[] }; truncated: boolean }
export interface HealthCheck { check_id: string; name: string; status: string; severity: 'INFO' | 'WARNING' | 'ERROR' | 'BLOCKED'; message: string; evidence: string | null }
export interface Dependency { name: string; version_specifier: string | null; declared: boolean; installed: boolean; installed_version: string | null; status: string; source_file: string | null; action: string; message: string | null }
export interface HealthReport { project_id: string; generated_at: string; environment: EnvironmentInfo; checks: HealthCheck[]; dependency_status: Dependency[]; truncated: boolean }
export interface DriftFinding { requirement_id: string; state: 'NO_DRIFT' | 'POTENTIAL_DRIFT' | 'CONFIRMED_STRUCTURAL_DRIFT' | 'UNRESOLVED'; reason: string; related_implementations: string[]; related_tasks: string[] }
export interface TimelineEvent { event_id: string; timestamp: string; event_type: string; title: string; description: string; related_requirement_ids: string[]; related_feature_ids: string[]; related_task_ids: string[] }
export interface ProjectState { project_info: ProjectInfo; scan_timestamp: string; git_available: boolean; counts: { files: number; python_modules: number; test_files: number }; files: { relative_path: string; file_type: string; size: number; is_test: boolean; is_source: boolean; is_config: boolean }[]; frameworks: string[]; dependencies: { name: string; version_specifier: string | null; source_file: string }[]; truncated: boolean }
export interface IntelligenceSnapshot { project_id: string; project_name: string; scan_timestamp: string; project_state_summary: Record<string, number>; blueprint_summary: Record<string, number>; traceability_summary: Record<string, number>; environment_summary: Record<string, boolean>; health_summary: Record<string, number>; requirement_summary: { total: number; by_verification_status: Record<string, number> }; drift_summary: DriftFinding[]; intelligence_summary: Record<string, string | number> | string }
export interface IntelligenceBundle { info: ProjectInfo; state: ProjectState; requirements: { items: Requirement[]; total: number; truncated: boolean }; blueprint: Blueprint; graph: TraceGraph; environment: EnvironmentInfo; health: HealthReport; snapshot: IntelligenceSnapshot; timeline: { items: TimelineEvent[]; total: number; truncated: boolean } }
